# Generated by Django 4.2.23 on 2025-08-17 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('face_shapes', models.JSONField(blank=True, default=list)),
                ('hair_types', models.JSONField(blank=True, default=list)),
                ('hair_lengths', models.JSONField(blank=True, default=list)),
                ('occasions', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hairstyles/%Y/%m/')),
                ('image_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hairstyles/thumbs/%Y/%m/')),
                ('tutorial_video_url', models.URLField(blank=True)),
                ('before_after_images', models.JSONField(blank=True, default=list)),
                ('maintenance', models.CharField(blank=True, max_length=16)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('professional', 'Professional Only')], default='medium', max_length=20)),
                ('estimated_time', models.PositiveIntegerField(blank=True, help_text='Time in minutes', null=True)),
                ('trend_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('popularity_score', models.FloatField(default=0.0)),
                ('seo_keywords', models.JSONField(blank=True, default=list)),
                ('styling_tips', models.TextField(blank=True)),
                ('products_needed', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trend_score', '-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('nb', 'Non-binary'), ('other', 'Other')], max_length=16)),
                ('occasions', models.JSONField(blank=True, default=list)),
                ('hair_type', models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily/Kinky')], max_length=16)),
                ('hair_length', models.CharField(choices=[('pixie', 'Pixie/Very Short'), ('short', 'Short'), ('medium', 'Medium/Shoulder Length'), ('long', 'Long'), ('extra_long', 'Extra Long')], max_length=16)),
                ('hair_color', models.CharField(blank=True, max_length=50)),
                ('lifestyle', models.CharField(blank=True, choices=[('active', 'Active/Sporty'), ('professional', 'Professional'), ('creative', 'Creative/Artistic'), ('casual', 'Casual/Relaxed')], max_length=20)),
                ('maintenance', models.CharField(choices=[('low', 'Low (Wash & Go)'), ('medium', 'Medium (Some Styling)'), ('high', 'High (Daily Styling)')], max_length=16)),
                ('budget_range', models.CharField(blank=True, max_length=20)),
                ('color_preference', models.CharField(blank=True, max_length=50)),
                ('avoid_styles', models.JSONField(blank=True, default=list)),
                ('preferred_stylists', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('face_detected', models.BooleanField(default=False)),
                ('face_count', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_shape', models.CharField(max_length=50)),
                ('face_shape_confidence', models.FloatField(default=0.0)),
                ('detected_features', models.JSONField(blank=True, default=dict)),
                ('candidates', models.JSONField(default=list)),
                ('recommendation_scores', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('shared_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairmixer_app.userpreference')),
                ('selected_hairstyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hairmixer_app.hairstyle')),
                ('uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairmixer_app.uploadedimage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HairstyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hairmixer_app.hairstylecategory')),
            ],
            options={
                'verbose_name_plural': 'Hairstyle Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hairstyle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hairmixer_app.hairstylecategory'),
        ),
        migrations.AddField(
            model_name='hairstyle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked', models.BooleanField()),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], null=True)),
                ('note', models.TextField(blank=True)),
                ('accuracy_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], null=True)),
                ('style_satisfaction', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hairstyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hairmixer_app.hairstyle')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairmixer_app.recommendationlog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CachedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('face_shape', models.CharField(max_length=50)),
                ('preference_hash', models.CharField(max_length=64)),
                ('recommendations', models.JSONField()),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='hairmixer_a_expires_c900a5_idx'), models.Index(fields=['face_shape', 'preference_hash'], name='hairmixer_a_face_sh_2145f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('image_upload', 'Image Upload'), ('recommendation_generated', 'Recommendation Generated'), ('style_clicked', 'Style Clicked'), ('overlay_generated', 'Overlay Generated'), ('feedback_submitted', 'Feedback Submitted'), ('share_clicked', 'Share Clicked')], max_length=30)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user', 'is_active'], name='hairmixer_a_user_id_dd66c4_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['created_at'], name='hairmixer_a_created_eda5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['user', 'created_at'], name='hairmixer_a_user_id_9d8112_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['processing_status'], name='hairmixer_a_process_f881ef_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', 'created_at'], name='hairmixer_a_user_id_1a5613_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['status'], name='hairmixer_a_status_8ddf7c_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['face_shape'], name='hairmixer_a_face_sh_911896_idx'),
        ),
        migrations.AddIndex(
            model_name='hairstyle',
            index=models.Index(fields=['is_active', 'trend_score'], name='hairmixer_a_is_acti_c195bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hairstyle',
            index=models.Index(fields=['category', 'is_active'], name='hairmixer_a_categor_05bf11_idx'),
        ),
        migrations.AddIndex(
            model_name='hairstyle',
            index=models.Index(fields=['is_featured'], name='hairmixer_a_is_feat_1b44a5_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user', 'created_at'], name='hairmixer_a_user_id_1b66a1_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['hairstyle', 'rating'], name='hairmixer_a_hairsty_d27240_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['is_public'], name='hairmixer_a_is_publ_1a4df6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'created_at'], name='hairmixer_a_event_t_18ee35_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'created_at'], name='hairmixer_a_user_id_cf24e6_idx'),
        ),
    ]
