# Generated by Django 4.2.23 on 2025-10-03 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0002_hairstyle_userpreference_uploadedimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='faceshape',
            field=models.CharField(blank=True, choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('oblong', 'Oblong'), ('diamond', 'Diamond'), ('triangle', 'Triangle')], max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='faceshape_confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hair_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged/Needs Care')], max_length=16),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hair_texture_detail',
            field=models.CharField(blank=True, choices=[('smooth', 'Smooth'), ('coarse', 'Coarse'), ('silky', 'Silky'), ('frizzy', 'Frizzy/Prone to Frizz'), ('normal', 'Normal')], max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hair_thickness',
            field=models.CharField(blank=True, choices=[('fine', 'Fine/Thin'), ('medium', 'Medium'), ('thick', 'Thick'), ('very_thick', 'Very Thick')], max_length=16),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hairstyle_family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hairstyle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='styling_maintenance',
            field=models.CharField(blank=True, choices=[('low', 'Low (Wash & Go)'), ('medium', 'Medium (Some Styling)'), ('high', 'High (Daily Styling)')], max_length=16),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='styling_preference',
            field=models.CharField(blank=True, choices=[('natural', 'Natural/Minimal Styling'), ('casual', 'Casual Styling'), ('polished', 'Polished/Professional'), ('glamorous', 'Glamorous/High Fashion'), ('edgy', 'Edgy/Alternative')], max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='volume',
            field=models.CharField(blank=True, choices=[('flat', 'Flat/No Volume'), ('light', 'Light Volume'), ('medium', 'Medium Volume'), ('high', 'High/Full Volume')], max_length=16),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='wants_bangs',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
