# Generated by Django 4.2.23 on 2025-10-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0003_userpreference_faceshape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_condition',
            field=models.CharField(blank=True, choices=[('none', 'None/Healthy'), ('damaged', 'Damaged'), ('dry_ends', 'Dry Ends'), ('oily_scalp', 'Oily Scalp'), ('dandruff', 'Dandruff'), ('frizzy', 'Frizzy'), ('split_ends', 'Split Ends'), ('thinning', 'Thinning'), ('sensitive_scalp', 'Sensitive Scalp')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_length',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_texture_detail',
            field=models.CharField(blank=True, choices=[('fine', 'Fine'), ('normal', 'Normal'), ('thick', 'Thick')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_thickness',
            field=models.CharField(blank=True, choices=[('thin', 'Thin'), ('medium', 'Medium'), ('thick', 'Thick')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_type',
            field=models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('moderate', 'Moderate'), ('relaxed', 'Relaxed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='styling_preference',
            field=models.CharField(blank=True, choices=[('natural', 'Natural'), ('classic', 'Classic'), ('elegant', 'Elegant'), ('trendy', 'Trendy'), ('edgy', 'Edgy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='volume',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16),
        ),
    ]
