# Generated by Django 4.2.23 on 2025-10-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0004_alter_userpreference_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='suitable_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], db_index=True, default='unisex', help_text='Target gender for this hairstyle', max_length=10),
        ),
    ]
