# Generated by Django 4.2.23 on 2025-10-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0006_convert_hair_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='faceshape',
            field=models.CharField(blank=True, choices=[('heart', 'Heart'), ('oblong', 'Oblong'), ('oval', 'Oval'), ('round', 'Round'), ('square', 'Square')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('auburn', 'Auburn'), ('gray', 'Gray'), ('white', 'White'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_condition',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_texture_detail',
            field=models.CharField(blank=True, choices=[('fine', 'Fine'), ('normal', 'Normal'), ('thick', 'Thick'), ('smooth', 'Smooth'), ('coarse', 'Coarse'), ('silky', 'Silky'), ('frizzy', 'Frizzy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_thickness',
            field=models.CharField(blank=True, choices=[('thin', 'Thin'), ('medium', 'Medium'), ('thick', 'Thick'), ('very_thick', 'Very Thick')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('professional', 'Professional'), ('creative', 'Creative'), ('casual', 'Casual'), ('moderate', 'Moderate'), ('relaxed', 'Relaxed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='styling_preference',
            field=models.CharField(blank=True, choices=[('natural', 'Natural'), ('casual', 'Casual'), ('classic', 'Classic'), ('polished', 'Polished'), ('elegant', 'Elegant'), ('glamorous', 'Glamorous'), ('trendy', 'Trendy'), ('edgy', 'Edgy')], max_length=20),
        ),
    ]
