# Generated by Django 4.2.23 on 2025-11-02 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0007_alter_userpreference_faceshape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(help_text="e.g., 'Professional Look', 'Casual Weekend'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this profile')),
                ('is_default', models.BooleanField(default=False, help_text='Use this profile by default')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-Binary'), ('other', 'Other')], default='female', max_length=20)),
                ('hair_type', models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily')], default='straight', max_length=20)),
                ('hair_length', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('very_long', 'Very Long')], default='medium', max_length=20)),
                ('hair_texture', models.CharField(choices=[('fine', 'Fine'), ('medium', 'Medium'), ('thick', 'Thick')], default='medium', max_length=20)),
                ('hair_condition', models.CharField(choices=[('healthy', 'Healthy'), ('dry', 'Dry'), ('oily', 'Oily'), ('damaged', 'Damaged'), ('color_treated', 'Color Treated')], default='healthy', max_length=20)),
                ('lifestyle', models.CharField(choices=[('active', 'Active'), ('professional', 'Professional'), ('casual', 'Casual'), ('creative', 'Creative')], default='casual', max_length=20)),
                ('maintenance_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('preferred_colors', models.JSONField(blank=True, default=list, help_text='Preferred hair colors')),
                ('avoid_styles', models.JSONField(blank=True, default=list, help_text='Styles to avoid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-last_used_at', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='hairmixer_a_user_id_f8ba9c_idx'), models.Index(fields=['user', '-last_used_at'], name='hairmixer_a_user_id_3271de_idx')],
                'unique_together': {('user', 'profile_name')},
            },
        ),
    ]
