# Generated by Django 4.2.23 on 2025-11-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0009_update_preferenceprofile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenceprofile',
            name='occasions',
            field=models.JSONField(blank=True, default=list, help_text='Multiple occasions for styling'),
        ),
    ]
