# Generated by Django 4.2.23 on 2025-11-04 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0010_preferenceprofile_occasions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedHairstyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hairstyle_name', models.CharField(max_length=200)),
                ('recommendation_data', models.JSONField(blank=True, default=dict, help_text='Full recommendation object including match scores, category, etc.')),
                ('user_preferences', models.JSONField(blank=True, default=dict, help_text='User preferences used to generate this recommendation')),
                ('face_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('face_shape_confidence', models.FloatField(blank=True, null=True)),
                ('overlay_url', models.CharField(blank=True, max_length=500, null=True)),
                ('personalized_description', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text="User's personal notes about this saved hairstyle")),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='hairmixer_app.hairstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_hairstyles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='hairmixer_a_user_id_15e3c2_idx'), models.Index(fields=['hairstyle', '-saved_at'], name='hairmixer_a_hairsty_610ce3_idx'), models.Index(fields=['user', 'hairstyle'], name='hairmixer_a_user_id_0117da_idx')],
            },
        ),
    ]
