# Generated by Django 4.2.23 on 2025-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0011_savedhairstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenceprofile',
            name='hair_color',
            field=models.CharField(choices=[('natural', 'Natural'), ('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('auburn', 'Auburn'), ('gray', 'Gray'), ('white', 'White'), ('other', 'Other')], default='brown', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('natural', 'Natural'), ('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('auburn', 'Auburn'), ('gray', 'Gray'), ('white', 'White'), ('other', 'Other')], max_length=50),
        ),
    ]
