# Generated by Django 4.2.23 on 2025-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0012_alter_preferenceprofile_hair_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenceprofile',
            name='styling_maintenance',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Daily styling time', max_length=20),
        ),
        migrations.AddField(
            model_name='preferenceprofile',
            name='wants_bangs',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
