# Generated by Django 4.2.23 on 2025-11-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0013_preferenceprofile_styling_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenceprofile',
            name='hair_color',
            field=models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('auburn', 'Auburn'), ('gray', 'Gray'), ('white', 'White'), ('natural', 'Natural'), ('other', 'Other')], default='brown', max_length=20),
        ),
        migrations.AlterField(
            model_name='preferenceprofile',
            name='lifestyle',
            field=models.CharField(choices=[('active', 'Active'), ('moderate', 'Moderate'), ('relaxed', 'Relaxed')], default='moderate', max_length=20),
        ),
    ]
