# Generated by Django 4.2.23 on 2025-11-27 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hairmixer_app', '0014_alter_preferenceprofile_hair_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairstyleLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='hairmixer_app.hairstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hairstyle_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'hairstyle'], name='hairmixer_a_user_id_4d5364_idx'), models.Index(fields=['hairstyle', 'reaction'], name='hairmixer_a_hairsty_b54ad0_idx')],
                'unique_together': {('user', 'hairstyle')},
            },
        ),
    ]
